name: dawurogna_figurative_speaking
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  go_router: ^16.0.0
  provider: ^6.1.5
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/book_icon.png
    - assets/images/dawuro_gihibli.png
    - assets/data/dawurogna_proverbs.json

  fonts:
    - family: Dash
      fonts:
        - asset: assets/fonts/Dash-Horizon-Demo.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth.ttf
